# Generated by Django 5.1.4 on 2025-09-09 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators_service', '0003_admin_admin_photo_admin_middle_name'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('ATHLETICS', 'Athletics'), ('VOLLEYBALL', 'Volleyball'), ('SWIMMING', 'Swimming')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='description',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default='00000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_admitted', to='moderators_service.admin'),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies_or_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='application_number',
            field=models.CharField(default='00000', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/birthcerts/'),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_allotted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='complexion',
            field=models.CharField(blank=True, choices=[('FAIR', 'Fair'), ('DARK', 'Dark'), ('CHOCOLATE', 'Chocolate'), ('OLIVE', 'Olive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ALUMNI', 'Alumni'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='has_sibling_here',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_class_completed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_school_attended',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/parent_ids/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/docs/passports/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('FRENCH', 'French'), ('SPANISH', 'Spanish'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_academic_report',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/reports/'),
        ),
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('CHRISTIANITY', 'Christianity'), ('ISLAM', 'Islam'), ('TRADITIONAL', 'Traditional'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sibling_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sibling_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='students/docs/transfers/'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='talents',
            field=models.ManyToManyField(blank=True, to='students.talent'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('DANCE', 'Dance'), ('DRAMA', 'Drama'), ('ART', 'Art'), ('DEBATE', 'Debate')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sports',
            field=models.ManyToManyField(blank=True, to='students.sport'),
        ),
    ]
