# Generated by Django 4.2.16 on 2024-10-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_school_registration_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
