# Generated by Django 4.2.16 on 2024-10-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_remove_user_school_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gateway.school'),
            preserve_default=False,
        ),
    ]
