# Generated by Django 5.1.4 on 2025-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_user_is_setup_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
