# Generated by Django 5.1.4 on 2025-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0013_alter_school_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
