# Generated by Django 5.1.4 on 2025-09-01 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gateway', '0014_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('biometric_data', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('grade', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3'), ('SHS 1', 'SHS 1'), ('SHS 2', 'SHS 2'), ('SHS 3', 'SHS 3')], max_length=50)),
                ('enrollment_date', models.DateField()),
                ('guardian_phone', models.CharField(max_length=15)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('biometric_data', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('subject_taught', models.CharField(max_length=255)),
                ('hire_date', models.DateField()),
                ('qualification', models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('Other', 'Other')], default='Diploma', max_length=100)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=100, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('teaching_load', models.PositiveIntegerField(blank=True, null=True)),
                ('certification_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('biometric_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='social_media',
            new_name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal_name',
        ),
        migrations.AddField(
            model_name='school',
            name='ai_analytics_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='biometric_integration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='school', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='vr_classroom_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='school',
            name='extra_curricular_activities',
        ),
        migrations.AlterField(
            model_name='school',
            name='facilities',
            field=models.CharField(blank=True, choices=[('Borehole', 'Borehole'), ('ICT Lab', 'ICT Lab'), ('Library', 'Library'), ('Science Lab', 'Science Lab'), ('Playground', 'Playground'), ('Dining Hall', 'Dining Hall')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='official_telephone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='population',
            field=models.CharField(choices=[('Below 100', 'Below 100'), ('101 - 500', '101 - 500'), ('501 - 1000', '501 - 1000'), ('1001 & above', '1001 & above')], default='Below 100', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('International', 'International'), ('Mission', 'Mission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_users', to='gateway.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default=None, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'user_type'], name='gateway_use_usernam_a862fc_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['email', 'registration_number'], name='gateway_sch_email_b050a3_idx'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='gateway.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='interests_talents',
            field=models.ManyToManyField(blank=True, to='gateway.talent'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='school',
            name='extra_curricular_activities',
            field=models.ManyToManyField(blank=True, to='gateway.extracurricularactivity'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone_number'], name='gateway_par_phone_n_dd33d3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='gateway_stu_student_533c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_id', 'phone_number'], name='gateway_tea_teacher_da56f6_idx'),
        ),
    ]
