# Generated by Django 5.1.4 on 2025-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0015_extracurricularactivity_parent_student_talent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Borehole', 'Borehole'), ('ICT Lab', 'ICT Lab'), ('Library', 'Library'), ('Science Lab', 'Science Lab'), ('Playground', 'Playground'), ('Dining Hall', 'Dining Hall')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='facilities',
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_classrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teachers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='population',
            field=models.CharField(blank=True, choices=[('Below 100', 'Below 100'), ('101 - 500', '101 - 500'), ('501 - 1000', '501 - 1000'), ('1001 & above', '1001 & above')], default='Below 100', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='gateway.facilitieschoice'),
        ),
    ]
