# Generated by Django 5.1.4 on 2025-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0017_school_website_alter_school_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='official_telephone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
