# Generated by Django 5.1.4 on 2025-09-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0018_alter_school_official_telephone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracurricularactivity',
            options={'ordering': ['name'], 'verbose_name': 'Extra-curricular Activity', 'verbose_name_plural': 'Extra-curricular Activities'},
        ),
        migrations.AlterModelOptions(
            name='facilitieschoice',
            options={'ordering': ['name'], 'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['user__username'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'other_names'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['name'], 'verbose_name': 'Talent', 'verbose_name_plural': 'Talents'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'other_names'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='parent',
            name='biometric_data',
            field=models.CharField(blank=True, help_text='Hashed clock-in data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text="Optional e.g., '5.6037° N, 0.1870° W'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='official_telephone_number',
            field=models.CharField(blank=True, help_text='Include country code if applicable.', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Can be set in Setup Step 2.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='biometric_data',
            field=models.CharField(blank=True, help_text='Hashed clock-in data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='School-specific or GES ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(help_text='GES registration number or internal ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
