# Generated by Django 5.1.4 on 2025-09-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0019_alter_extracurricularactivity_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='students.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
