# Generated by Django 5.1.4 on 2025-09-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0020_alter_parent_students_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
