# Generated by Django 5.1.4 on 2025-09-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_sport_alter_student_options_alter_talent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('biometric_data', models.CharField(blank=True, help_text='Hashed clock-in data', max_length=255, null=True)),
                ('students', models.ManyToManyField(related_name='parents', to='students.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['phone_number'], name='parents_ser_phone_n_094402_idx')],
            },
        ),
    ]
