# Generated by Django 5.1.4 on 2025-09-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('teacher_id', models.CharField(help_text='GES registration number or internal ID', max_length=50, unique=True)),
                ('subject_taught', models.CharField(max_length=255)),
                ('hire_date', models.DateField()),
                ('qualification', models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('Other', 'Other')], default='Diploma', max_length=100)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Humanities', 'Humanities'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=100, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('teaching_load', models.PositiveIntegerField(blank=True, null=True)),
                ('certification_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('biometric_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['last_name', 'other_names'],
                'indexes': [models.Index(fields=['teacher_id', 'phone_number'], name='teachers_se_teacher_e46770_idx')],
            },
        ),
    ]
