# Generated by Django 4.2.16 on 2024-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='can_manage_communications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_manage_facilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_manage_finances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_manage_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Principal', 'Principal'), ('AcademicAdmin', 'Academic Admin'), ('StudentServicesAdmin', 'Student Services Admin'), ('HRAdmin', 'Human Resource Admin'), ('FinanceAdmin', 'Finance Admin'), ('ITAdmin', 'IT Admin'), ('FacilitiesAdmin', 'Facilities and Operations Admin'), ('PRAdmin', 'Public Relations Admin')], max_length=50),
        ),
    ]
