# Generated by Django 5.1.2 on 2024-10-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0002_admin_can_manage_communications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
        migrations.AddField(
            model_name='admin',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
